---
- hosts: devops
  become: true
    #vars_files:
    #- vars/default.yml
  tasks:
    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.0.1/docker-compose-linux-x86_64
        dest: "/usr/local/bin/docker-compose"
        mode: 0755
